// <auto-generated />
using System;
using Examen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250407225815_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Analyse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BilanCodeInfirmier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BilanCodePatient")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("BilanDatePrelevement")
                        .HasColumnType("datetime2");

                    b.Property<int>("BilanId")
                        .HasColumnType("int");

                    b.Property<int>("DureeResultat")
                        .HasColumnType("int");

                    b.Property<int?>("LaboratoireId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValeurAnalyse")
                        .HasColumnType("real");

                    b.Property<float>("ValeurMaxNormale")
                        .HasColumnType("real");

                    b.Property<float>("ValeurMinNormale")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoireId");

                    b.HasIndex("BilanCodeInfirmier", "BilanCodePatient", "BilanDatePrelevement");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Bilan", b =>
                {
                    b.Property<string>("CodeInfirmier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodePatient")
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DatePrelevement")
                        .HasColumnType("datetime2");

                    b.HasKey("CodeInfirmier", "CodePatient", "DatePrelevement");

                    b.HasIndex("CodePatient");

                    b.ToTable("Bilans");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Infirmier", b =>
                {
                    b.Property<string>("CodeInfirmier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeInfirmier");

                    b.ToTable("Infirmiers");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Laboratoire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AdresseLabo");

                    b.HasKey("Id");

                    b.ToTable("Laboratoires");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Patient", b =>
                {
                    b.Property<string>("CodePatient")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Informations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodePatient");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Analyse", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Laboratoire", "Laboratoire")
                        .WithMany("Analyses")
                        .HasForeignKey("LaboratoireId");

                    b.HasOne("Examen.ApplicationCore.Domain.Bilan", "Bilan")
                        .WithMany("Analyses")
                        .HasForeignKey("BilanCodeInfirmier", "BilanCodePatient", "BilanDatePrelevement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bilan");

                    b.Navigation("Laboratoire");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Bilan", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Infirmier", "Infirmier")
                        .WithMany("Bilans")
                        .HasForeignKey("CodeInfirmier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Patient", "Patient")
                        .WithMany("Bilans")
                        .HasForeignKey("CodePatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Infirmier");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Bilan", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Infirmier", b =>
                {
                    b.Navigation("Bilans");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Laboratoire", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Patient", b =>
                {
                    b.Navigation("Bilans");
                });
#pragma warning restore 612, 618
        }
    }
}
